---
name: Main Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup workspace
        uses: ./.github/actions/setup-workspace

      - name: Install linters
        run: |
          pip install --upgrade pip
          pip install pre-commit==3.5.0

      - name: Install dependencies
        run: |
          just tidy
          go install golang.org/x/tools/cmd/goimports@latest
          go install github.com/fzipp/gocyclo/cmd/gocyclo@latest

      - name: Run linters
        run: pre-commit run --all-files

  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run setup
        uses: ./.github/actions/setup-workspace

      - name: Run tests
        run: |
          go clean -testcache
          go test -v -cover -race ./...
